const normalize = (value) => String(value ?? '').trim();

export const slugFromEventTitle = (title) => {
  const t = normalize(title).toLowerCase();
  const explicit = {
    '100 metres': '100-metres',
    '400 metres': '400-metres',
    shotput: 'shotput',
    'relay race': 'relay-race',
    'hit the wicket': 'hit-the-wicket',
    cricket: 'cricket',
    football: 'football',
    badminton: 'badminton',
    chess: 'chess',
    carrom: 'carrom',
    'table tennis': 'table-tennis',
    'tug o war': 'tug-o-war',
    'tug of war': 'tug-o-war',
  };
  if (explicit[t]) return explicit[t];

  return t
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
};

export const EVENT_DETAILS = {
  cricket: {
    title: 'Cricket',
    rules: [
      'Full swing of the arm and side-arm bowling are restricted.',
      'Heel rising is not allowed. During bowling, no steps will be allowed.',
      'A six will be considered as OUT.',
      'A six will not be considered as OUT in a no-ball, but no runs will be given to the batting team for the boundary (only the no-ball 1 run will be given).',
      'A minimum of 8 players is mandatory to play the match, and 2 players will be substitutes. The absence of any main player for more than 2 minutes will lead to a walkover.',
      'No bye runs will be given, but overthrow runs and wide runs are allowed.',
      'LBW out is not considered.',
      'All matches will be of 5 overs (bowling restrictions: 2+1+1+1).',
      "If possible, semi-final and final matches will be of 6 overs (2+2+1+1).",
      'Only one bouncer is allowed per over.',
      "The umpire's decision will be considered final. Any type of misbehavior with umpires or committee members may cause penalty runs for the team accordingly.",
      'ID proof (ID card/Library card/Money receipt) is mandatory.',
      'You are requested to reach sharp at 9:00 AM.',
      'Every team must report 30 minutes earlier than their scheduled match. If any team fails to report on time, overs may be reduced for that team, and the opponent team may get a walkover.',
    ],
    eventHeads: [],
  },
  chess: {
    title: 'Chess',
    rules: [
      'Each player will have 5 minutes (5+0) (no extra time added) to finish their game in the first round (Blitz format).',
      'If the game is tied, there will be a tiebreaker match with 1 minute per player (1+0) (Bullet format, no extra time).',
      'Winners will be decided by either checkmate or time running out.',
      'The color (Black or White) will be chosen by a coin toss.',
      'If a player touches a piece, they must move or capture it if it is a legal move.',
      'Players must press the clock with the same hand they used to move the piece.',
      "The clock should be placed on Black’s right and White’s left.",
      "Players are allowed two illegal moves. After two warnings, if a third illegal move happens, the opponent wins—but the opponent must stop the clock and tell the organizers. Organizers won’t step in unless the opponent claims it.",
      'In the second round, each player will have 5 minutes with a 3-second bonus (5+3) per move. If it’s a draw, a 3-minute tiebreaker (3+0) (no extra time) will be played. From the third round onwards, each match will be 10 minutes (10+0) (no extra time), with a 5-minute (5+0) tiebreaker (no extra time) if needed.',
      'In the quarterfinals, there will be one game of 10 minutes with a 2-second bonus per move (10+2), and a tiebreaker of 5 minutes with a 2-second bonus (5+2). In the semifinals and final, two games will be played (one with Black, one with White) following FIDE rules, with 10 minutes and a 2-second bonus (10+2), plus a tiebreaker of 5 minutes and a 2-second bonus (5+2) if required.',
      'ID proof (like an ID card, library card, or receipt) is required.',
      'Please arrive on time.',
    ],
    eventHeads: [],
  },
  'table-tennis': {
    title: 'Table Tennis',
    rules: [
      'Scoring: A point is awarded for every successful serve and return that the opponent fails to play back. The first player to reach 11 points wins the game, with a two-point lead needed if the score reaches 10-10 (deuce).',
      "Serving: The server must toss the ball vertically at least 16 cm and hit it so it first bounces on their side of the table and then on the opponent's side.",
      'Returning: The receiver must hit the ball after it bounces once on their side.',
      'Faults: A point is awarded to the opponent if a player fails to return the serve or shot.',
      'Faults: A point is awarded to the opponent if a player hits the ball twice consecutively.',
      'Faults: A point is awarded to the opponent if a player hits the ball with their body or clothing.',
      'Faults: A point is awarded to the opponent if a player serves illegally.',
      'Faults: A point is awarded to the opponent if a player touches the net with their hand or racket during play.',
      'Faults: A point is awarded to the opponent if a player hits the ball off the table.',
      'Players switch ends after every game in a best-of-three, five, or seven match format.',
      'ID proof (ID card/Library card/money receipt) is mandatory.',
      'You are requested to reach sharp at 9:30 AM.',
    ],
    eventHeads: [],
  },
  badminton: {
    title: 'Badminton',
    rules: [
      'A point is awarded for every rally won. Each game is played to 21 points, with a two-point lead required to win. If the score reaches 20–20, play continues until one side leads by two points. A match is typically played as best of three games.',
      "Serving: The serve must be hit diagonally across the court and below the server’s waist level. The server must have both feet stationary on the ground during the serve. The shuttle should not touch the net or land outside the service court.",
      'Returning: The receiver must return the shuttle before it touches the ground, and alternate hits between players must continue until the rally ends.',
      'Faults: A point is awarded to the opponent if a player fails to return the shuttle within the opponent’s court.',
      'Faults: A point is awarded to the opponent if a player touches the net with their racket, body, or clothing.',
      'Faults: A point is awarded to the opponent if a player hits the shuttle twice consecutively.',
      'Faults: A point is awarded to the opponent if a player strikes the shuttle before it crosses to their side.',
      'Faults: A point is awarded to the opponent if a player deliberately distracts or obstructs the opponent.',
      'Faults: A point is awarded to the opponent if a player serves or receives service from the wrong side or improperly.',
      'Court Change: Players must switch sides after the first game, and in the deciding game (third game, if applicable) when one side reaches 11 points.',
      'Equipment & Conduct: Players are expected to bring their own rackets; shuttles will be provided by the organizers. Proper sports attire and non-marking shoes are mandatory.',
      'ID Verification: College ID card/Library card/Money receipt must be presented before the match. Entry without valid ID will not be permitted.',
    ],
    eventHeads: [],
  },
  carrom: {
    title: 'Carrom',
    rules: [
      'Match will be played in doubles and played by Board Method.',
      'Each interested participant needs to fill up the form and provide the details with correct identity proof.',
      'Both team members should be present at the said time only and no change is allowed after filling the Google form, otherwise the team will be disqualified.',
      'No on-spot registration is allowed (registration must be done in Google form before deadline).',
      'Teams must carry their ID proof (ID card/money receipt/library card) for verification.',
      'All teams are requested to reach sharp 9:00 AM.',
      'The decision of the committee members and the event coordinators will be final.',
      'Board Rules: Each game contains three boards to play their opponent team; each board will be played for 3 minutes.',
      'Board Rules: At first two boards will be played without queen. If the results of the two boards are tied then the third board will be played with Queen & Cover Rule.',
    ],
    eventHeads: [
      { name: 'Pritam Basak', extra: 'CSE-DS (4th Year) — Contact: 8910254870' },
      { name: 'Himagna Mallik', extra: 'AIML (4th Year) — Contact: 9732132009' },
      { name: 'Srimoyee Pal', extra: 'CSE (3rd Year) — Contact: 8584018858' },
    ],
  },
  football: {
    title: 'Football',
    rules: [
      'Minimum 7 players required to play the match (we can consider at least 6 players to kick off in case of any discrepancy).',
      'A team can have maximum of 3 rolling substitutes.',
      'Each half time will be of 10 minutes. 1 minute break between the half. No extra time will be given.',
      "Referee's decision will be final on the field.",
      'No studs are allowed. Only joggers or barefoot.',
      'If any team will not present within 5 mins of their match commencement, it will be straight declared as walkover.',
      'No offside rule.',
      'In case of draw, 3 penalties will be taken from each team (only the playing 7 players can take penalties). If still draw, then 2 sudden death penalties will be taken. If still draw, the winner will be decided through coin toss (no step penalty will be allowed).',
      'ID proof (ID card/Library card/money receipt) is mandatory at the time of field verification.',
      'All teams are requested to reach sharp at 9:00 AM.',
      'Matches will start from 9:30 AM onwards.',
      "A hard copy of the team list (signed by respective department's HOD/sports faculty member) should be submitted on the field at the time of verification (mandatory).",
    ],
    eventHeads: [],
  },
  'tug-o-war': {
    title: 'Tug O War',
    rules: [
      'Team composition: 6 players per team.',
      'Maximum 2 substitutes.',
      'Match format: Best of 3 rounds.',
      '2 minutes per round.',
      '1 minute break between rounds.',
      'Winning criteria: Pull the opponent team past the boundary line.',
      'Win 2 rounds to win the match.',
      "Start signal: Match starts only on referee’s command.",
      'Early pull = foul.',
      'Footwear & safety: Sports shoes compulsory.',
      'Gloves allowed (no sticky substances).',
      'Fouls (not allowed): Sitting, kneeling, or lying.',
      'Fouls (not allowed): Wrapping rope around body or arms.',
      'Fouls (not allowed): Digging ground or external support.',
      'Fouls (not allowed): Unsporting behavior.',
      'Penalties: First foul – warning.',
      'Penalties: Second foul – round loss.',
      'Penalties: Serious misconduct – disqualification.',
      'Reporting time: Teams must report 10 minutes before match time.',
      "Referee decision: Referee’s decision will be final.",
    ],
    eventHeads: [],
  },
  'hit-the-wicket': {
    title: 'Hit the Wicket',
    rules: [
      'Each participant will get 3 throws.',
      'The objective is to hit the wicket (stumps) with the ball.',
      'All throws must be made from behind the marked throwing line.',
      'Running is strictly prohibited before or during the throw.',
      'Only one ball per attempt is allowed.',
      'Distance between the throwing line and wicket: 10 meters (standard). Organizers may adjust based on age group if required.',
      'The wicket must remain fixed and upright.',
      'A direct hit is valid.',
      'Only one bounce before hitting the wicket is permitted.',
      'More than one bounce: invalid hit and no points awarded, even if the wicket falls.',
      'Announcements: First Attempt → “First Chance”, Second Attempt → “Second Chance”, Third Attempt → “Third Chance”.',
      'Scoring: Hit in 1st chance → 3 points; 2nd chance → 2 points; 3rd chance → 1 point; no hit in all 3 → 0 points.',
      'Valid throw: Throw behind the line; no running; direct hit or only one bounce.',
      'Invalid throw: Running before throwing; crossing the line; more than one bounce.',
      'Result & ranking: Total points will be calculated for each participant.',
      'Winner: Highest score. Runner-up: Second highest score.',
      'Tie-breaker: Player with fewer attempts ranks higher. If still tied, one extra throw will decide the position.',
    ],
    eventHeads: [],
  },

  // Placeholder pages for athletics items not specified yet.
  '100-metres': { title: '100 metres', rules: [], eventHeads: [] },
  '400-metres': { title: '400 metres', rules: [], eventHeads: [] },
  shotput: { title: 'Shotput', rules: [], eventHeads: [] },
  'relay-race': { title: 'Relay Race', rules: [], eventHeads: [] },
};
